# SpeechBrain  unit tests to ease continuous integration
# NOTE: Caching these offers no speedup
name: SpeechBrain toolkit CI

# Runs on pushes to master and all pull requests
on:    # yamllint disable-line rule:truthy
    push:
        branches: [main, develop]
    pull_request:

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.12]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: pip
                  # cache for {lint-,ci-,}requirements.txt
                  cache-dependency-path: |
                      *requirements.txt
            - name: Install sox
              run: |
                  sudo apt-get update
                  sudo apt install sox libsox-dev
            # Installing only SoX for now due to FFmpeg issues on the CI server with Torchaudio 2.1.
            # FFmpeg works fine on all other machines. We'll switch back when the CI server is fixed.
            #- name: Install ffmpeg
            #  run: |
            #      sudo apt-get update
            #      sudo apt-get install -y ffmpeg
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            - name: Full dependencies
              run: |
                  pip install torch==2.2.1+cpu torchaudio==2.2.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu ctc-segmentation kaldilm==1.15.1 spacy==3.7.4 flair==0.13.1 -r requirements.txt --editable . --no-dependencies k2==1.24.4.dev20240223+cpu.torch2.2.1 --find-links https://k2-fsa.github.io/k2/cpu.html
            - name: Consistency tests with pytest
              run: |
                  pytest tests/consistency
            - name: Unittests with pytest
              run: |
                  pytest tests/unittests
            - name: Doctests with pytest
              run: |
                  pytest --doctest-modules speechbrain
            - name: Integration tests with pytest
              run: |
                  pytest tests/integration
