name: Verify docs generation

# Runs on pushes to master and all pull requests
on:    # yamllint disable-line rule:truthy
    push:
        branches: [main, develop]
    pull_request:

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'
                  cache: pip
                  # cache for {docs-,lint-,ci-,}requirements.txt
                  cache-dependency-path: |
                      docs/docs-requirements.txt
                      *requirements.txt
            - name: Full dependencies
              run: |
                  # up to k2 compatible torch version
                  pip install torch==2.2.1+cpu torchaudio==2.2.1+cpu --index-url https://download.pytorch.org/whl/cpu
                  pip install k2==1.24.4.dev20240223+cpu.torch2.2.1 --find-links https://k2-fsa.github.io/k2/cpu.html
                  pip install -r requirements.txt
                  pip install -r docs/docs-requirements.txt
                  pip install --editable . --no-dependencies
            - name: Generate docs
              run: |
                  cd docs
                  make html
